export const CREATIVE_WILDCARDS = [
    "Focus on the lighting",
    "Focus on the kitchen",
    "Focus on the view/windows",
    "Focus on the flooring",
    "Focus on the storage/space",
    "Tone: Humorous/Self-deprecating",
    "Tone: Aggressive Sales",
    "Tone: Whisper/ASMR",
    "Tone: Luxury/Sophisticated",
    "Tone: Fast-paced/Energetic",
    "Mention the neighborhood",
    "Mention the potential ROI",
    "Mention the lifestyle",
    "Mention the 'hidden gem' aspect",
    "Use a 'Warning' hook",
    "Use a 'Did you know?' hook",
    "Use a 'Stop scrolling' hook",
    "Use a 'Question' hook",
    "Use a 'Storytime' intro",
    "Use a 'Secret' angle",
    "Highlight a specific flaw as a feature",
    "Compare to a hotel",
    "Compare to a previous sale",
    "Focus on the bathroom/spa",
    "Focus on the outdoor space",
    "Focus on the technology/smart home",
    "Address a specific objection (e.g. price)",
    "Use a seasonal reference",
    "Make a pop culture reference",
    "Use a 'POV' style",
    "Use a 'Day in the life' style"
];

export const VIRAL_STRATEGIES = [
    "The Price Reveal",
    "The Failure/Trip",
    "The Mystery Door",
    "The Hidden Room",
    "The Luxury Flex",
    "The Value Shock",
    "The Lifestyle Tease",
    "The Neighborhood Secret",
    "The Renovation Potential",
    "The Cozy Vibes"
];
